SELECT * FROM ALL_TABLES;
DROP TABLE REPLY;

CREATE TABLE BOARD(
	ID INT PRIMARY KEY, 
	TITLE VARCHAR(30),
	WRITER VARCHAR(15),
	CONTENT VARCHAR(100),
	WDATE DATE DEFAULT SYSDATE
);
-- CREATE
INSERT INTO BOARD (id, title,writer,content) VALUES (1,'Title1','an','Test1');
-- READ
SELECT * FROM BOARD;

CREATE TABLE MEM(
	ID VARCHAR(15) PRIMARY KEY, 
	PASSWORD VARCHAR(10),
	NAME VARCHAR(15),
	ROLE VARCHAR(15)
);
-- CREATE
INSERT INTO MEM VALUES('an','11','사용자','user');
INSERT INTO MEM VALUES('admin','1004','관리자','admin');
-- READ
SELECT * FROM MEM;